version: "3"

services:
  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/logs:/var/log/nginx
    ports:
      - 80:80
      - 81:81
    links:
      - web
      - php

  php:
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www
    environment:
      XDEBUG_CONFIG: "remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - postgres
      - redis

  postgres:
    image: postgres:11.3
    volumes:
      - ./data/postgres/database:/var/lib/postgresql/data
    ports:
      - 54321:5432
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app

  redis:
    image: redis:3.0
    volumes:
      - redis:/data
    ports:
      - 63791:6379

  web:
    image: node:12.4-alpine
    working_dir: /var/www/web
    volumes:
      - ./web:/var/www/web
    environment:
      - HOST=0.0.0.0
    command: sh -c "yarn install && yarn dev"

volumes:
  database:
    driver: local
  redis:
    driver: local
